language: nix

sudo: required

env:
  global:
    secure: ZjKyH4jaLRCkiwyRyTXM84oK2dIu5YSpzl1ckU8QtQTXB7zSG3tyfnrSlrPFonBz9/YtRFLqbjCU1G/5UddIFjsNEWzQIkq6JAPR30A42gy6lldibdotvjQpVuYXd8udYqJY6sWKvzXYWJfsE8U0g3MiilLHrzJd0hX8jdB1n4LrQzvNQdDzUc/wjx3dktQ/oyKHOSld5/KnX7XS00CHcgGIJuds3GvlturZ6jzInHFbRrncOBr4urRUUq2sQD47mnRNB+/dUdqu+wmLTvqKJ1Tt0W1t4Y87ZbAV3N5oNMORmerrjNU8nwR29dDbG1tLWzip0tYlLDJ4soo2NOaocrMYvwze7taxnb/2qT2pI6QLQ+A3OJt3m4mk+e9moV5UEZiBvvv2plKCn3YS74JE3/UfAVyg5wou80phmzqLLU8up+T6JlzRV4wVmJiz9mrQvGA8Bss2dI3C5RFX5H72VXXogyy0GHAnPyTPEYZvU93/DTx68iFCGgZCVuiUKI3NDz95hLI7JltXLe68m8BgMSN97RohiV7sd38IMbXv/wQYVu37LnlwYXMNtfHrNfg0osjtmmQvAOKFnaVNxMPtU+0rAY+GhetKWxmjLMO4vlUnvHfxrud0ulJoG2cHPp2lv56NoQJnozm0X+UZs4Mmwnv3fWHFm+eHS2cY653t2dQ=

install:
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs-unstable
  - nix-channel --add https://nixos.org/channels/nixos-unstable nixos-unstable
  - nix-channel --add https://nixos.org/channels/nixos-unstable-small nixos-unstable-small
  - nix-channel --update

script:
  - df -h
  - nix-collect-garbage -d
  - df -h
  - "./scripts/run.sh packages nixos-unstable"
  - "./scripts/run.sh packages nixos-unstable-small"
  - "./scripts/run.sh packages nixpkgs-unstable"
  - "./scripts/run.sh options nixos-unstable"
  - "./scripts/run.sh options nixos-unstable-small"
  - "./scripts/run.sh options nixpkgs-unstable"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  on:
    all_branches: true
  local-dir: result
